# Vowel Counter
# Count vowels in a string

ask "Enter text:"
set text to answer

set vowels to 0
set len to (length of text)

for i from 1 to len
  set char to (letter i of text)

  if char = "a" then
    change vowels by 1
  end

  if char = "e" then
    change vowels by 1
  end

  if char = "i" then
    change vowels by 1
  end

  if char = "o" then
    change vowels by 1
  end

  if char = "u" then
    change vowels by 1
  end

  # Uppercase
  if char = "A" then
    change vowels by 1
  end

  if char = "E" then
    change vowels by 1
  end

  if char = "I" then
    change vowels by 1
  end

  if char = "O" then
    change vowels by 1
  end

  if char = "U" then
    change vowels by 1
  end
end

say join "Vowels: " and vowels
say join "Consonants: " and (len - vowels)
